CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra -pedantic

TARGET = dynarr_app
OBJS = main.o dynarr.o

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) -o $(TARGET)

main.o: main.cpp dynarr.h
	$(CXX) $(CXXFLAGS) -c main.cpp

dynarr.o: dynarr.cpp dynarr.h
	$(CXX) $(CXXFLAGS) -c dynarr.cpp

clean:
	rm -f $(OBJS) $(TARGET)
